services:
  postgres:
    image: 'pgvector/pgvector:pg16'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=exambot'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      org.springframework.boot.service-connection: postgres